version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    environment:
      - DEFAULT_HOST=api-proxy
      - VIRTUAL_HOST=nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  api-proxy:
    image: lelylanlab/api-proxy:latest
    restart: always
    expose:
      - 8000
    depends_on:
      - people
      - devices
      - types
      - subscriptions
      - profiles
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=api-proxy
      - VIRTUAL_PORT=8000
      - PORT=8000
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=user
      - MEMCACHIER_PASSWORD=password
      - LELYLAN_PEOPLE_PORT=80
      - LELYLAN_DEVICES_PORT=80
      - LELYLAN_TYPES_PORT=80
      - LELYLAN_SUBSCRIPTIONS_PORT=80
      - LELYLAN_PROFILES_PORT=80
      - LELYLAN_PROXY_URL=api-proxy
  devices:
    image: lelylanlab/devices:latest
    restart: always
    expose:
      - 80
    depends_on:
      - mongodb
      - redis
      - memcached
      - people
      - types
      - subscriptions
      - profiles
    environment:
      - VIRTUAL_HOST=devices
      - PORT=80
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=user
      - MEMCACHIER_PASSWORD=password
  mqtt:
    image: lelylanlab/mqtt:latest
    restart: always
    expose:
      - 80
    depends_on:
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=mqtt
      - REDIS_HOST=redis
      - DEBUG=lelylan
      - NODE_PORT=1883
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=user
      - MEMCACHIER_PASSWORD=password
  nodes:
    image: lelylanlab/nodes:latest
    restart: always
    expose:
      - 8000
    depends_on:
      - mongodb
      - redis
      - memcached
      - api-proxy
      - mqtt
    environment:
      - VIRTUAL_HOST=nodes
      - VIRTUAL_PORT=8000
      - PORT=8000
      - MOSCA_HOST=mqtt
      - REDIS_HOST=redis
      - LELYLAN_API_URL=api-proxy
      - LELYLAN_API_HOST=api-proxy
      - DEBUG=lelylan
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=user
      - MEMCACHIER_PASSWORD=password
  people:
    image: lelylanlab/people:latest
    restart: always
    expose:
      - 80
    depends_on:
      - types
      - subscriptions
      - profiles
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=people
      - PORT=80
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=user
      - MEMCACHIER_PASSWORD=password
      - LELYLAN_DEV_URL=dev-center
      - LELYLAN_DEV_PORT=80
  physicals:
    image: lelylanlab/physicals:latest
    restart: always
    expose:
      - 80
    depends_on:
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=physicals
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=user
      - MEMCACHIER_PASSWORD=password
  profiles:
    image: lelylanlab/profiles:latest
    restart: always
    expose:
      - 80
    depends_on:
      - types
      - subscriptions
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=profiles
      - PORT=80
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=user
      - MEMCACHIER_PASSWORD=password
  subscriptions:
    image: lelylanlab/subscriptions:latest
    restart: always
    expose:
      - 80
    depends_on:
      - types
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=subscriptions
      - PORT=80
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=user
      - MEMCACHIER_PASSWORD=password
  types:
    image: lelylanlab/types:latest
    restart: always
    expose:
      - 80
    depends_on:
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=types
      - PORT=80
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=user
      - MEMCACHIER_PASSWORD=password
  webhooks:
    image: lelylanlab/webhooks:latest
    restart: always
    expose:
      - 80
    depends_on:
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=webhooks
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=user
      - MEMCACHIER_PASSWORD=password
  websockets:
    image: lelylanlab/websockets:latest
    restart: always
    expose:
      - 8000
    depends_on:
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=websockets
      - VIRTUAL_PORT=8000
      - PORT=8000
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=user
      - MEMCACHIER_PASSWORD=password

  #: Development tools
  types-dashboard:
    image: lelylanlab/types-dashboard-ng:latest
    restart: always
    expose:
      - 80
    depends_on:
      - api-proxy
      - people
      - websockets
    environment:
      - VIRTUAL_HOST=types-dashboard
      - PORT=80
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_API_PUBLIC_URL=api-proxy
      - LELYLAN_PEOPLE_PUBLIC_URL=people
      - LELYLAN_CLIENT_ID=""
      - LELYLAN_TYPES_DASHBOARD_PUBLIC_URL=types-dashboard
      - LELYLAN_WEBSOCKETS_PUBLIC_URL=websockets
  devices-dashboard:
    image: lelylanlab/devices-dashboard-ng:latest
    restart: always
    expose:
      - 80
    depends_on:
      - api-proxy
      - people
      - websockets
    environment:
      - VIRTUAL_HOST=devices-dashboard
      - HOST=devices-dashboard
      - PORT=80
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_API_PUBLIC_URL=api-proxy
      - LELYLAN_PEOPLE_PUBLIC_URL=people
      - LELYLAN_CLIENT_ID=""
      - LELYLAN_DEVICES_DASHBOARD_PUBLIC_URL=devices-dashboard
      - LELYLAN_WEBSOCKETS_PUBLIC_URL=websockets
  dev-center:
    image: lelylanlab/dev:latest
    restart: always
    expose:
      - 80
    depends_on:
      - people
    environment:
      - VIRTUAL_HOST=dev-center
      - PORT=80
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_PEOPLE_PORT=80

  mongodb:
    image: mongo:2.6
    restart: always
    volumes_from:
      - mongodb-data
    expose:
      - 27017
  mongodb-data:
    image: mongo:2.6
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb
    entrypoint: /bin/true
  redis:
    image: redis:2.6
    restart: always
    volumes_from:
      - redis-data
    expose:
      - 6379
  redis-data:
    image: redis:2.6
    volumes:
      - /data
    entrypoint: /bin/true
  memcached:
    image: bitnami/memcached:latest
    restart: always
    expose:
      - 11211
    environment:
      - MEMCACHED_USERNAME=user
      - MEMCACHED_PASSWORD=password
